defaults:
  - grasp_model: dngf_6d
  - generator_grasp: dngf
  - nerf_model: 1_view
  - optimizer_config: 2_images_6d
optimizer_name: grasp_1_view
model_path: /home/hephaestus/workspace/data/models/grasp/simple/dngf_1_view_ebm_6d
backbone_path: /home/hephaestus/workspace/data/models/nerf/simple/1_view