defaults:
  - grasp_model: grasp
  - generator_grasp: grasp
  - nerf_model: 1_view
  - optimizer_config: 2_images_6d
model_path: /home/hephaestus/workspace/data/models/grasp/simple/grasp_1_view_ce
backbone_path: /home/hephaestus/workspace/data/models/nerf/simple/1_view