apiVersion: v1
kind: Pod
metadata:
  name: clip-nerf-inference-1
  namespace: robot-experiments
  labels:
    clip-nerf-inference/type: pod
spec:
  containers:
  - name: inference-server-container
    image: universalrobotcell1/inference-server:tf-v2.11.0
    imagePullPolicy: Always
    ports:
    - containerPort: 8076
      protocol: TCP
    resources:
      limits:
        cpu: 19200m
        memory: 41231686041600Mi
        nvidia.com/gpu: "1"
      requests:
        cpu: "16"
        memory: 32Gi
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: "/home/jovyan/data/"
      name: clip-nerf-inference-storage
  volumes:
  - name: clip-nerf-inference-storage
    persistentVolumeClaim:
      claimName: clip-nerf-inference-pvc