apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clip-nerf-inference-pvc
  namespace: robot-experiments
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi