apiVersion: v1
kind: Pod
metadata:
  name: fastapi-2
  namespace: robot-experiments
  labels:
    name: fastapi-pod-2
spec:
  containers:
  - name: fastapi-2
    image: gergelysoti/inference_server:2024-2-0.9
    ports:
      - containerPort: 8076
    resources:
      limits:
        cpu: 19200m
        memory: 41231686041600m
        nvidia.com/gpu: "1"
      requests:
        cpu: "16"
        memory: 32Gi
        nvidia.com/gpu: "1"
    volumeMounts:
      - mountPath: "/home/jovyan/data/"
        name: gergely-soti-shared-data-pvc-robot-experiments
  volumes:
    - name: gergely-soti-shared-data-pvc-robot-experiments
      persistentVolumeClaim:
        claimName: gergely-soti-shared-data-pvc-robot-experiments

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: fastapi-pod-2
  name: fastapi-2
  namespace: robot-experiments
spec:
  ports:
  - nodePort: 31706
    port: 8076
    protocol: TCP
    targetPort: 8076
  selector:
    name: fastapi-pod-2
  type: NodePort
